name: Publish CWE-25 Docker Image to GHCR

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  publish-cwe-798:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/M-Faheem-Khan/publish-packages/cwe-25
          tags: type=sha

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container for CWE-25(linux/amd64)
        uses: docker/build-push-action@v4
        with:
          context: ./CWE-25/
          file: ./CWE-25/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cwe-789